language: php

php:
  - 7.0

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: LmdCXUEX5iPt/+3pQ7PSqni5WNR1xexgU0f8UvpbXDKob7DfVkIL7Yb5Im6GxuYmYb/9ta+qAOFbG0TRMLAbmGAmpf5ejk1vWf9BmD1YtvT3Vd/z3pzr9alFxt5ZZ16L+VxZnrwNBCk9zB+7sx1bqdaVBdv5lpNv8eMeKNAbyp4/N0hRHROBXMCviCckH1ZOVRM9l32WG0/TKBw/5Dfg7sDxl1tvk74uTbAs/EgPWhtcCJFaszqqfd54fqbnoWAsEAJI0tBXEXbc9QCxKtzm1Ra4QR4zMrlXcHxcfHL5O6uiEAz7/yb0KO0IHbmIbiJan1OsXs6VIGEw+bJWbcS2bnezLIIIuhlKg9vXg3J/2jz6JT/WLkIzQyThCPfL4HVXFXfypJRKtJEJF4TjPU9luN5AsK8koSzsNYvQPwlx8U/i4rN9Zfp70tjlMWgxWLFpGHH5YbIF6xt70ZHMmPfMhusGPnExUG62LpqjfiJ2/aceEYwqb8/2K2ujJllfxqf8Wo1pi0hp0Q4J0UqkhUjJS4+Pm7hyNjcQRhh1gxNdLGsBPt5Cx5JhUdGAY0v0bYo2sWQXNu4NvFlc8ePpMz3UszeO8jHtVf77pQ8PLgTOvUZUP9iMQPIBe8k5wCiFsMFLBbH5y6HnnDUqO16Xe8X3HQ15npnPptSkr/LZ1nussQg=
